watch:
  sampling_rate: 100 # Hz, resample to this frequency by interpolation
  round_digits: 4 # all sensor values are rounded to this number of decimal digits after interpolation
  msec_offset: 435974339335
  output_format: '.parquet'

sensorlogger:
  sampling_rate: 100 # Hz, resample to this frequency by interpolation
  round_digits: 4 # all sensor values are rounded to this number of decimal digits after interpolation
  msec_offset: -78772
  output_format: '.parquet'

cam:
  data_timezone: 7 # time zone in video filename
  msec_offset: 0
  output_format: '.mp4'

timerapp:
  msec_offset: 0
  output_format: '.csv'
